### ISSUE TITLE
Deployment of hive on an ipv6 setup fails: Back-off pulling image "registry.svc.ci.openshift.org/openshift/hive-v4.0:hive

### ISSUE THREAD

**Issue by achuzhoy** [openshift/hive#932] opened 2020-04-07 14:04 UTC
Version: 4.4.0-0.nightly-2020-04-04-025830
Deployed setup with ipv6.
Attempted to deploy hive.

[kni@provisionhost-0-0 ~]$ oc get pod -n hive
NAME                             READY   STATUS             RESTARTS   AGE
hive-operator-7b7f6fc44d-cj8h4   0/1     ImagePullBackOff   0          10h
[kni@provisionhost-0-0 ~]$ 

[kni@provisionhost-0-0 ~]$ oc describe pod hive-operator-7b7f6fc44d-cj8h4 -n hive
Name:         hive-operator-7b7f6fc44d-cj8h4
Namespace:    hive
Priority:     0
Node:         worker-0-1.ocp-edge-cluster-0.qe.lab.redhat.com/fd2e:6f44:5dd8::128
Start Time:   Tue, 07 Apr 2020 03:20:31 +0000
Labels:       control-plane=hive-operator
              controller-tools.k8s.io=1.0
              pod-template-hash=7b7f6fc44d
Annotations:  k8s.ovn.org/pod-networks:
                {"default":{"ip_address":"fd01::5:4497:d6ff:fe00:84/64","mac_address":"46:97:d6:00:00:84","gateway_ip":"fd01:0:0:5::1"}}
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "ovn-kubernetes",
                    "interface": "eth0",
                    "ips": [
                        "fd01::5:4497:d6ff:fe00:84"
                    ],
                    "mac": "46:97:d6:00:00:84",
                    "dns": {}
                }]
              openshift.io/scc: restricted
Status:       Pending
IP:           fd01::5:4497:d6ff:fe00:84
IPs:
  IP:           fd01::5:4497:d6ff:fe00:84
Controlled By:  ReplicaSet/hive-operator-7b7f6fc44d
Containers:
  hive-operator:
    Container ID:  
    Image:         registry.svc.ci.openshift.org/openshift/hive-v4.0:hive
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/services/hive-operator
      --log-level
      info
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     100m
      memory:  256Mi
    Liveness:  http-get http://:8080/debug/health delay=10s timeout=1s period=10s #success=1 #failure=1
    Environment:
      CLI_CACHE_DIR:  /var/cache/kubectl
    Mounts:
      /var/cache/kubectl from kubectl-cache (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hive-operator-token-dqq7h (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kubectl-cache:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  hive-operator-token-dqq7h:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hive-operator-token-dqq7h
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                     From                                                      Message
  ----     ------   ----                    ----                                                      -------
  Normal   BackOff  9m17s (x2789 over 10h)  kubelet, worker-0-1.ocp-edge-cluster-0.qe.lab.redhat.com  Back-off pulling image "registry.svc.ci.openshift.org/openshift/hive-v4.0:hive"
  Warning  Failed   4m17s (x2812 over 10h)  kubelet, worker-0-1.ocp-edge-cluster-0.qe.lab.redhat.com  Error: ImagePullBackOff
[kni@provisionhost-0-0 ~]$ oc get pod -n hive
NAME                             READY   STATUS             RESTARTS   AGE
hive-operator-7b7f6fc44d-cj8h4   0/1     ImagePullBackOff   0          10h
[kni@provisionhost-0-0 ~]$

**Comment by staebler** [comment] 2020-04-07 14:11
This should be fixed with https://github.com/openshift/hive/pull/896.

**Comment by staebler** [comment] 2020-04-08 17:39
I did not read the issue carefully enough. It is not related to #908.

The cause of this issue is that the default Hive image being used is not accessible from the cluster. In this case, there is another registry housing the Hive image that is accessible. The replacement image can be specified by setting the `DEPLOY_IMAGE` environment variable when running `make deploy`.

/close

**Closed** 2020-04-08 17:40 UTC
