### ISSUE TITLE
cannot create sync set instance

### ISSUE THREAD

**Issue by itdove** [openshift/hive#808] opened 2020-02-07 18:24 UTC
Hi,

version hive v1
I want to deploy a cluster on AWS, the deployment succeeded. Then we create a synset but get the following error in the hive controller:
```
time="2020-02-07T18:05:26Z" level=info msg="reconciling sync sets for cluster deployment" clusterDeployment=itdove/itdove11 controller=syncset
time="2020-02-07T18:05:26Z" level=error msg="cannot create sync set instance" clusterDeployment=itdove/itdove11 controller=syncset error="the server does not allow this method on the requested resource (post syncsetinstances.hive.openshift.io)" syncSetInstance=itdove/itdove11-itdove11-multicluster-endpoint-syncset
```

All hive CRs (cd, imageset,...) are create in the same namespace.

I deployed hive using the `make deploy` on a Openshift cluster.

Any idea?

cheers
Dominique

**Comment by staebler** [comment] 2020-02-07 19:12
This is likely an RBAC issue. Can you verify that you have the `manager-role` ClusterRole and the `manager-rolebinding` ClusterRoleBinding and that the `hive-controllers` deployment is set to use the `default` service account? The ClusterRole and ClusterRoleBinding should have been set up for you as part of the `make deploy`.

**Comment by staebler** [comment] 2020-02-07 19:15
Well, I guess that the provisioning of the cluster would not have worked very well without the ClusterRole. So I suspect that the ClusterRole is present. Can you show me what the yaml for the ClusterRole is?

**Comment by itdove** [comment] 2020-02-07 19:28
kubectl get clusterrole manager-role -o yaml

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"creationTimestamp":null,"name":"manager-role"},"rules":[{"apiGroups":["batch"],"resources":["jobs"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":[""],"resources":["serviceaccounts","secrets","configmaps","events","persistentvolumeclaims"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":[""],"resources":["pods","namespaces"],"verbs":["get","list","watch"]},{"apiGroups":["rbac.authorization.k8s.io"],"resources":["roles","rolebindings"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterdeployments","clusterdeployments/status","clusterdeployments/finalizers"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterprovisions"],"verbs":["get","list","watch","create"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterimagesets"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterimagesets/status"],"verbs":["get","update","patch"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterdeprovisions","clusterdeprovisions/finalizers"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterdeprovisions/status"],"verbs":["get","update","patch"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterprovisions","clusterprovisions/status","clusterprovisions/finalizers"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["hive.openshift.io"],"resources":["machinepools","machinepools/status","machinepools/finalizers"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["batch"],"resources":["jobs"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterstates","clusterstates/status"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["hive.openshift.io"],"resources":["dnszones","dnszones/status","dnszones/finalizers"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterdeployments"],"verbs":["get","watch","update"]},{"apiGroups":["hive.openshift.io"],"resources":["syncsets"],"verbs":["get","create","update","delete","patch","list","watch"]},{"apiGroups":["hive.openshift.io"],"resources":["syncidentityproviders"],"verbs":["get","list","watch"]},{"apiGroups":["hive.openshift.io"],"resources":["selectorsyncidentityproviders"],"verbs":["get","list","watch"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterdeployments"],"verbs":["get","list","watch"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterdeployments"],"verbs":["get","list","watch"]},{"apiGroups":["hive.openshift.io"],"resources":["syncsets"],"verbs":["get","create","update","delete","patch","list","watch"]},{"apiGroups":["hive.openshift.io"],"resources":["selectorsyncsets"],"verbs":["get","create","update","delete","patch","list","watch"]},{"apiGroups":["hive.openshift.io"],"resources":["syncsetinstances","syncsetinstances/status"],"verbs":["get","create","update","delete","patch","list","watch"]},{"apiGroups":["hive.openshift.io"],"resources":["clusterdeployments","syncsets"],"verbs":["get","list","watch","create","update"]},{"apiGroups":["velero.io"],"resources":["backups"],"verbs":["create"]}]}
  creationTimestamp: "2019-11-13T16:24:25Z"
  name: manager-role
  resourceVersion: "54229494"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/manager-role
  uid: 0edcee7a-0632-11ea-b161-025a1e91c929
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - secrets
  - configmaps
  - events
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  - clusterdeployments/status
  - clusterdeployments/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterprovisions
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterimagesets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterimagesets/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeprovisions
  - clusterdeprovisions/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeprovisions/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterprovisions
  - clusterprovisions/status
  - clusterprovisions/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hive.openshift.io
  resources:
  - machinepools
  - machinepools/status
  - machinepools/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterstates
  - clusterstates/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hive.openshift.io
  resources:
  - dnszones
  - dnszones/status
  - dnszones/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  verbs:
  - get
  - watch
  - update
- apiGroups:
  - hive.openshift.io
  resources:
  - syncsets
  verbs:
  - get
  - create
  - update
  - delete
  - patch
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - syncidentityproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - selectorsyncidentityproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - syncsets
  verbs:
  - get
  - create
  - update
  - delete
  - patch
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - selectorsyncsets
  verbs:
  - get
  - create
  - update
  - delete
  - patch
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - syncsetinstances
  - syncsetinstances/status
  verbs:
  - get
  - create
  - update
  - delete
  - patch
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  - syncsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - create
```

**Comment by itdove** [comment] 2020-02-11 19:10
I don't know if it is related to my issue but is it normal that the bindata.go for the `manager-rolebinding` as for subjects namespace "system" and the hive_controllers_role_binding.yaml is kustomized with namespace: hive?

**Comment by itdove** [comment] 2020-02-11 20:51
@dgoodwin Any idea?

**Comment by dgoodwin** [comment] 2020-02-13 13:23
The bindata is probably correct, I believe the base files are generated by the kubebuilder/controller-runtime stack and point to those namespaces by default, and then we customize to point them to the correct place.

Everything else looks right, based on the above it looks like your controllers pod should definitely have perms to write syncsetinstance. Not sure what's going on there.

**Comment by dgoodwin** [comment] 2020-02-13 13:25
Shot in the dark, does deleting the hive-controllers pod help?

What version of OpenShift are we running on? 

Was this deployed from the master or v1 branch? Sounds like v1, but should use master going forward as of Monday fwiw.

**Comment by dgoodwin** [comment] 2020-02-13 13:30
Could you get us a dump of all the logs for all pods in the hive namespace.

**Comment by itdove** [comment] 2020-02-13 13:34
1) Shot in the dark, does deleting the hive-controllers pod help? No
2) What version of OpenShift are we running on? 4.2
3) Was this deployed from the master or v1 branch? Sounds like v1, but should use master going forward as of Monday fwiw: Initial deployment was done with v1 but switched Tuesday on master... maybe some leftover?

**Comment by dgoodwin** [comment] 2020-02-13 14:39
From the hiveadmission logs: E0213 13:48:47.939114       1 authentication.go:65] Unable to authenticate the request due to an error: x509: certificate signed by unknown authority

That looks like it could definitely cause the error in your hive-controllers log.

Appears this is caused by the issue Chris raised this morning.

**Comment by itdove** [comment] 2020-02-13 14:48
I agree we have to fix that but the "not allowed" issue rose before that error.

**Comment by itdove** [comment] 2020-02-13 21:43
We used another cluster with hive on it and we didn't get the above error "Not allowed"... 
ClusterVersion was 4.2 on both.

@chrisahl which image you used to deploy hive?

**Comment by chrisahl** [comment] 2020-02-14 02:56
@itdove I used hive v1-alpha-2020-02-12

**Comment by itdove** [comment] 2020-02-14 13:37
Seems this problem is either linked to master or to that specific environment.

**Comment by gregsheremeta** [comment] 2020-05-18 20:55
sounds like this was environment or image specific. Closing, but feel free to reopen if this is still an issue

**Closed by gregsheremeta** 2020-05-18 20:55 UTC
